on:
  push:
    branches:
      - "master"

name: "Continuous Deployment - Build"

jobs:
  build:
    name: "Build Docker Image"

    runs-on: ubuntu-latest

    env:
      DOCKER_BUILDX_VERSION: '0.3.1'

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Docker Login"
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u ${{ github.event.repository.owner.login }} --password-stdin

      - name: Set up Docker Buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest

      - name: "Build Docker Image"
        run: .build/test.sh

      - name: "Docker Logs"
        if: always()
        run: sudo journalctl -xe -u docker