on:
  push:
    branches:
      - "master"

name: "Continuous Deployment - Build"

jobs:
  build:
    name: "Build Docker Image"

    runs-on: ubuntu-latest

    env:
      DOCKER_BUILDX_VERSION: '0.3.1'

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Docker Login"
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u ${{ github.event.repository.owner.login }} --password-stdin

      - name: "Install Docker Buildx"
        run: |
          mkdir -p ~/.docker/cli-plugins
          curl -fsSL -o ~/.docker/cli-plugins/docker-buildx "https://github.com/docker/buildx/releases/download/v${DOCKER_BUILDX_VERSION}/buildx-v${DOCKER_BUILDX_VERSION}.linux-amd64"
          chmod +x ~/.docker/cli-plugins/docker-buildx
          docker buildx create --name builder --use

      - name: "Build Docker Image"
        run: .build/test.sh

      - name: "Docker Logs"
        if: always()
        run: sudo journalctl -xe -u docker